# Generated by Django 5.0.6 on 2024-07-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='temp_order_id', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
